### ISSUE TITLE
Crashes 1.14.

### ISSUE THREAD

**Issue by Blayyke** [Fabric-Mods/Dark-Elevators#2]
Here's the log: https://gist.github.com/Blayyke/ad24f09e4267c559ef186408b5109193
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/block/FabricBlockSettings
		at net.darkhax.elevators.block.ElevatorBlock.<init>(ElevatorBlock.java:24)

**Comment by darkhax** [comment]
Thanks for the report, but 1.14 is not officially supported at this time. Only 18w50a and 18w02a are.
